language: ruby
rvm:
  - 1.9.3

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -U postgres -c 'create database myplaceonline_test'

script: 
  - RAILS_ENV=test bundle exec rake db:setup
  - psql -U postgres -d myplaceonline_test -c "\\dt"
  - RAILS_ENV=test bundle exec rake test

after_failure:
  - psql -U postgres -d myplaceonline_test -c "\\dt"
