language: ruby
rvm:
  - 2.1.1

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -U postgres -c 'create database myplaceonline_test'

script: 
  - RAILS_ENV=test bundle exec rake db:setup test

after_failure:
  - psql -U postgres -d myplaceonline_test -c "\\dt"
