# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a9ca377037adb016d27a6b898e4d8b174e20ca6aaa7c79977603d036b7f199284dabd4122d22e432ee588346da428ca61175c0dc59d829137585d1bd66b5f6

test:
  secret_key_base: 14be7990b31f2ca0e45dd6682d2a76f71a9ab807cc3968d6740bc01bf1ffa32125ad9c14873768fe2af1a4c253a1732d2418e676a5d23bdf8c960088691d7406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
